# Generated by Django 5.1.2 on 2024-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_create_at_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Baslik'),
        ),
    ]
