# Generated by Django 5.1.2 on 2024-11-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
